### ISSUE TITLE
Software bugs in hyperOS systems

### ISSUE THREAD

**Issue by A1eeeee** [jd1378/otphelper#106]
After turning on the app with self-starting and unrestricted permissions
If one percent of the phone's battery enters the minimalist mode, and then the charge is restored, the app will not start automatically, and the phone needs to click once.
Or manually stop running the app will not start automatically.

**Comment by jd1378** [comment]
well, I'm not sure if I can do anything about what hyperOS decides to do with apps
please let me know if you have any ideas

btw I am on HyperOS and android 14 and I had no problem with the app so far

**Comment by jd1378** [comment]
can you try [1.16.0-rc](https://github.com/jd1378/otphelper/releases/tag/v1.16.0-rc)?

**Comment by A1eeeee** [comment]
> can you try [1.16.0-rc](https://github.com/jd1378/otphelper/releases/tag/v1.16.0-rc)? there's a small fix in it's notification listener which may solve your issue你可以试试 1.16.0-rc 吗？它的通知侦听器中有一个小修复，可以解决您的问题

ok ，thanks

**Comment by jd1378** [comment]
Hey
today I experienced the same problem
I will release an update (1.16.0-rc4) soon, which along with adding the auto start permission (check https://dontkillmyapp.com/xiaomi), seems to work good on Hyper OS 

I'll make a comment again when it's released.

**Comment by A1eeeee** [comment]
> released: [v1.16.0-rc4](https://github.com/jd1378/otphelper/releases/tag/v1.16.0-rc4)

thanks,The bug was resolved

**Comment by A1eeeee** [comment]
> released: [v1.16.0-rc4](https://github.com/jd1378/otphelper/releases/tag/v1.16.0-rc4)

Now, the problem of manually deactivating the app and not starting automatically has been solved. However, if the phone has 1% battery left, enters the minimalist mode, and then recharges it back to normal mode, the app still can't start automatically.

**Comment by jd1378** [comment]
Well there's really nothing more I can do

Please don't let it reach 1%, it's very bad for your battery 😁

**Comment by A1eeeee** [comment]
> Well there's really nothing more I can do好吧，我真的无能为力了
> 
> Please don't let it reach 1%, it's very bad for your battery 😁请不要让它达到 1%，这对您的电池😁非常不利

ok,This software is very easy to use. Thank you for your efforts. But this one I think is more like a bug in the system, because it causes many of my apps to not start normally.
