### ISSUE TITLE
Read Notifications Permission not allowed

### ISSUE THREAD

**Issue by reinhard-weber** [jd1378/otphelper#11]
Hi and thanks for developing this useful app! Actually with the newest version from f-Droid it's not possible to set "Read Notifications" - the Android-Button is greyed out and ends with the message "_For security reasons, this setting is currently not available_". This issue is not present in the version from Google Play... BR, Reinhard

**Comment by jd1378** [comment]
Hi
some times you have to go to the app settings and enable "Allow restricted settings"
I had included a note about this in permissions page when on Xiaomi phones (which was the only phone I observed this behavior)
but if your phone is not xiaomi and you are having this issue, please check the settings I mentioned above and check if you can enable the read notification permission again

and please tell me your phone brand, so I can show the note to other users as well

**Comment by reinhard-weber** [comment]
Thanks for your quick reply! Enabling "Allow restricted settings" worked fine on my Sony 1 IV (XQ-CT54) and your app now works like a charm :)

BR, Reinhard

________________________________
Von: javad mnjd ***@***.***>
Gesendet: Mittwoch, 11. Oktober 2023 10:51
An: jd1378/otphelper
Cc: reinhard-weber; Author
Betreff: Re: [jd1378/otphelper] Read Notifications Permission not allowed (Issue #11) 

Hi
some times you have to go to the app settings and enable "Allow restricted settings"
I had included a note about this in permissions page when on Xiaomi phones (which was the only phone I observed this behavior)
but if your phone is not xiaomi and you are having this issue, please check the settings I mentioned above and check if you can enable the read notification permission again

and please tell me your phone brand, so I can show the note to other users as well

**Comment by jd1378** [comment]
I'm glad it works now
thanks for the quick reply

**Comment by reinhard-weber** [comment]
Hi! Yes of course. It's

- Android 13
- Build 64.1.A.0.977
- Kernel 5.10.136-android12-9-00001-g987d4745ed78-ab10458915

Hope this helps! BR, Reinhard

________________________________
Von: javad mnjd ***@***.***>
Gesendet: Mittwoch, 11. Oktober 2023 11:09
An: jd1378/otphelper
Cc: reinhard-weber; Author
Betreff: Re: [jd1378/otphelper] Read Notifications Permission not allowed (Issue #11) 

can you mention on which android version are you as well ? this helps me determine if it's a new feature of android 13 or 12
thank you

**Comment by jd1378** [comment]
thank you! it sure helps
