### ISSUE TITLE
Test Notification custom text

### ISSUE THREAD

**Issue by nvllz** [jd1378/otphelper#113]
With the introduction of the new custom sensitive/ignored word list, it would be great to make the Send Test Notification button show a custom notification text dialog so users can quickly test their preferred keywords.

**Comment by jd1378** [comment]
while it sounds good at first, I can't imagine a good UI for it at the moment, and the extra work does not make sense to me as one can just simply send a message using telegram, sms or sth else to test it. so I don't think I'm gonna implement this.

I appreciate the thought though.
