### ISSUE TITLE
Add About page 

### ISSUE THREAD

**Issue by inson1** [jd1378/otphelper#12]
There should be
1. Author contact
2. Github source code
3. Translation link
4. Licence
5. App version

**Comment by jd1378** [comment]
I'll try to make the page with Source code link, license and app version for next version

and what do you mean by translation link

**Comment by BackMountainDevil** [comment]
I think that will make this app complex. Less is more.

App version can be found in app manager or system manager. Author contact and Github source code can be found by search the package name on Bing(or google).

**Comment by jd1378** [comment]
but not everyone can do things you mentioned, I'd say roughly 95% of people don't know what a package name is, let alone searching the package name.

I think maybe a subtle icon button at a corner, leading to about page maybe a nice way to add it (not sure though, just an idea)
it won't necessarily make the app more complex

**Comment by inson1** [comment]
> I think that will make this app(or service) complex. Less is more.
> 
> App version can be found in app manager or system manager. Author contact and Github source code can be found by search the package name on Bing(or google). License can be found in the github repo
> 

 I dont think info icon on right top of page is going to make it too much complex. 
Its still important info about the app. 
Yes you can find it somewhere else, but it would be nice find it on one place in the app.

Imho if I find bug/idea for feature request, when I'm using the app, its nice just click on link in About page. Same with app version.

The app is also on Google Play, so you have to think about newbies. 

Its just easier for everyone imho.

**Comment by inson1** [comment]
> and what do you mean by translation link 

@jd1378 I created issue for that #15

**Comment by jd1378** [comment]
created an about page in v1.4.0
