### ISSUE TITLE
Self ignore crash

### ISSUE THREAD

**Issue by solokot** [jd1378/otphelper#124]
If add the "OTP Helper" to the application ignore list from the test notification, then when you try to open the "Ignore List", the application closes silently. I am attaching the logcat. App version 1.16 from GitHub. Android 11 MIUI OS.
[logcat_07-20-2024_12-05-36.txt](https://github.com/user-attachments/files/16319560/logcat_07-20-2024_12-05-36.txt)

**Comment by jd1378** [comment]
uh
I'm so sorry
this only needs a quick fix

**Comment by jd1378** [comment]
released [v1.16.1](https://github.com/jd1378/otphelper/releases/tag/v1.16.1) with the fix

**Comment by jd1378** [comment]
thank you for the report
