### ISSUE TITLE
Interface layout issues

### ISSUE THREAD

**Issue by solokot** [jd1378/otphelper#125]
The screenshots show interface layout flaws caused by unaccounted long string lengths.
Unfortunately, for example, phrases in Russian are 20-30% longer than similar ones in English in symbol terms, and it is impossible to significantly shorten them while remaining correct and understandable.
App version 1.16. Phone display size 6,39″

![Screenshot_2024-07-20-11-39-41-883_io github jd1378 otphelper](https://github.com/user-attachments/assets/984db178-8820-4697-95d5-e84cbafe5ce3)
![Screenshot_2024-07-20-11-40-31-064_io github jd1378 otphelper](https://github.com/user-attachments/assets/cc389d33-9d6a-48ae-bd73-fa7c7118f457)

**Comment by jd1378** [comment]
thanks for reporting the issue
I'll look into it today

**Comment by jd1378** [comment]
fixed in [1.16.2](https://github.com/jd1378/otphelper/releases/tag/v1.16.2)
