### ISSUE TITLE
UI translate seems missing in Ignored List

### ISSUE THREAD

**Issue by BackMountainDevil** [jd1378/otphelper#14]
As you can see in the image, you could might only know a word 'title'.

![截图_2023-10-14_19-54-38](https://github.com/jd1378/otphelper/assets/59185302/2694760a-a5a2-4f08-8129-fa6094f2b7d7)

I am sure I do not translate `test_notification_title` startwith `title`, I translate it into "这是一条用来测试验证码提取的通知".

So I guess:
1. it use sms title to ignore
2. forget to add the `title` into translate keys, that is not found in string.xml

so I have a question, should we add a new translate key to title?

**Comment by jd1378** [comment]
Hi !
I'm sorry, the ignore list screen is somewhat incomplete
there's "tag:", "app:" and "nid:" as well, and they don't make sense to users,
so I should have taken time to properly make a component that reflects the item of the list
"title:" is part of detection mechanism,
to show the list correctly I have to make an extra component and show what it's using to ignore the said notification

so yeah, But I should make the component first, and I'm a bit busy right now, so it may take a while

**Comment by jd1378** [comment]
this should be resolved in upcoming version (1.16.0)
