### ISSUE TITLE
Android 15 problems

### ISSUE THREAD

**Issue by w9925** [jd1378/otphelper#140]
Since android 15 it is no longer working.
I am using GrapheneOS.

**Comment by jd1378** [comment]
Hi
thanks for reporting the issue
I'll try to take a look when I have the time

**Comment by jd1378** [comment]
:)) 
google manages to break stuff every single time
the app cannot access the notification content anymore
while debugging the app, when a sensitive notification is posted and I try to read the content, this is the text it returns now:
```
Sensitive notification content hidden
```

so basically app does not have access to the notification content anymore. I wonder if there's a settings inside OS for such apps.

**Comment by jd1378** [comment]
the solution for now is to disable enhanced notifications from settings:
![Screenshot_1729262311](https://github.com/user-attachments/assets/c82dd216-04df-46c7-ab89-5f2b3b10fe78)
