### ISSUE TITLE
Not Working on Android 14

### ISSUE THREAD

**Issue by Humorist2601** [jd1378/otphelper#17]
Hello

For some reason, after updating to the latest Graphene OS version (Android 14), the app has stopped working. I have tried reinstalling the app but it doesn't even recognize the test notification

All the permissions have been granted

**Comment by jd1378** [comment]
Hi
sorry that I missed this issue for so long
did you give up or did it work for you ?

I would like to know if your language was english or something elese as well

**Comment by Humorist2601** [comment]
No need for sorry, my account was flagged so the issue was not visible to you previously. 

The app has been working on the Android 14 for sometime so I guess we can close this issue now.
