### ISSUE TITLE
Code not detected in menoramivt sms

### ISSUE THREAD

**Issue by Dev-iL** [jd1378/otphelper#18]
First of all, thanks for the app! Below are SMS contents that didn't trigger the app (v.1.3.0):

```
492609 הנו קוד האימות החד פעמי שלך לכניסה לאזור האישי באתר מנורה מבטחים.
@www.menoramivt.co.il #492609
```

**Comment by jd1378** [comment]
Hi
what is the word in your language that almost always when present, there is a code as well ?
like for example right now in english, if there's the word "otp" there is almost always a code in the message
what's yours ? we will use that to detect that this message contains a code
is it "האימות החד פעמי" ?
the shorter the expression, the more messages it can detect

**Comment by Dev-iL** [comment]
Thank you for the clarification!
The phrase you mentioned means "one-time verification"; from what I observed in several examples, this full form is not typically present. I would go with one of the following:
- קוד אימות
- קוד האימות
- קוד
(Translation in order: verification code, the verification code, code)
I think the first two are about equally likely to appear. The last and shortest option is always present, but I suppose it might result in false positives in some  rare cases.

**Comment by jd1378** [comment]
I have tried to mitigate most of false positives through other means
So i guess we'll go with the last one 

I can add test for possible false positives if you provide me some examples that may trigger it

**Comment by Dev-iL** [comment]
I found another expression that may appear instead of "קוד": words that contain "סיסמ", e.g. הסיסמה, הסיסמא, סיסמתך. So that would be another regex. If it matters, קוד should appear at the end of the token (might come in the form הקוד)

I was about to add some "positive" tests:

```
  @Test
  fun hebrewCode1() {
    val msg = "סיסמתך היא: 123456"
    assertEquals(false, CodeIgnore.shouldIgnore(msg))
    assertEquals("123456", CodeExtractor.getCode(msg))
  }
  
  @Test
  fun hebrewCode2() {
    val msg = "קוד הכניסה שלך הוא 123456"
    assertEquals(false, CodeIgnore.shouldIgnore(msg))
    assertEquals("123456", CodeExtractor.getCode(msg))
  }
```
Can't think of any false positives at the moment. Will open another issue if something comes up.

**Comment by jd1378** [comment]
release in [v1.4.0](https://github.com/jd1378/otphelper/releases/tag/v1.4.0)

**Comment by Dev-iL** [comment]
Mamnoon!
