### ISSUE TITLE
[BUG] Color of texts doesnt (fully) change in Dark theme

### ISSUE THREAD

**Issue by inson1** [jd1378/otphelper#19]
I hope it isnt fixed in new version, it still isnt in F-Droid
Sometimes it is fully "white",  sometimes are also few texts black
![Screenshot_2023-10-22-14-53-13-769_io github jd1378 otphelper](https://github.com/jd1378/otphelper/assets/75314629/ea77f704-d3c7-4042-a46d-60b7931988b3)

**Comment by jd1378** [comment]
This is weird
I am not setting the color manually, i wonder whats happening
 Maybe a bug in jetpack compose

I have to release another version even if its not fixed in the latest release

**Comment by jd1378** [comment]
let me know if this is still an issue
