### ISSUE TITLE
A-Trust / Handy-Signatur

### ISSUE THREAD

**Issue by mkg20001** [jd1378/otphelper#21]
In Austria there is a service called Handy-Signatur (Phone Signature)

The OTP messages look as follows

```
Handy-Signatur für
 eid.oesterreich.gv.at
Vergleichswert
 v 7 n M Z S S H 6 l
TAN
 4 u 8 k u f
Bitte überprüfen Sie alle Werte!
(5 Min. gültig)
```

Where `4 u 8 k u f` is the OTP Code

Could you add support for this please?

**Comment by jd1378** [comment]
Hi
This is a tough one, I don't think i can add support for this specifically, since I can't find an anchor and also the code has spaces and its alphanumeric, which makes it much harder

btw, What does TAN mean ?

**Comment by mkg20001** [comment]
Transaktionsnummer eng Transaction number but its basically an OTP named differently

`[a-z0-9] [a-z0-9]

**Comment by mkg20001** [comment]
other tans are always 6 characters, letters and numbers uppercase/lowercase and maybe have spaces between each character

**Comment by jd1378** [comment]
I don't mean it's not possible to capture this case when its only this case alone, i mean supporting this one while supporting all other cases is the hard part
Otherwise doing this alone is super easy for me

**Comment by jd1378** [comment]
If you look at the code, theres only two regexes, and second one only runs if theres a sensitive keyword ever found

This is to keep this app efficient, because it runs the regex everytime there's a notification, which means hundreds of times for some people
Thats why it has to be: 1. General 2. Efficient
To be useful for everyone

**Comment by mkg20001** [comment]
I found a way to do it with the regex in #22. This includes general support for codes with spaces, without breaking other things
