### ISSUE TITLE
OTP identification is incorrect

### ISSUE THREAD

**Issue by duc2ht** [jd1378/otphelper#25]
Hello, I am a user from Vietnam. When using your app, I found the application doesn't recognize or misidentified the otp code. The otp code should have been 572123 but the application recognized it as 1533. Below is the SMS content in my language (Vietnamese):

_GD truc tuyen VietinBank,ma GD 1533 ma OTP 572123 so tien 50000 tai web MOMOCE.QK tuyet doi KHONG cung cap OTP cho nguoi khac_

Translate into English by Google translate: "VietinBank online transaction, transaction number 1533, OTP number 572123, amount 50,000 at MOMOCE website. Dear customers, DO NOT provide OTP to others"

As for other message content, the application does not recognize any OTP code:

_Tai khoan quy khach se bi tru 6000000 VND qua kenh giao dich truc tuyen. Neu dung, quy khach thuc hien nhap OTP 840348 de hoan tat. Neu khong, LH 19009247_

Translate into English: "Your account balance will be deducted 6000000 VND via online transaction channel.  If using, customers need to enter OTP 840348 to complete.  If not, contact 19009247"

Same thing happens with this message, the app doesn't recognize any code:

_QK nhap ma OTP 771808 tuong ung voi ma giao dich 7709 de cap lai mat khau dich vu VietinBank iPay.TH QK khong thuc hien giao dich nay, LH 1900558868_ 

Trans to Eng: "QK enters OTP code 771808 corresponding to transaction code 7709 to re-cap the VietinBank iPay service.TH QK cannot execute this transaction, contact 1900558868"

Sorry my English is not good, hope you understand

**Comment by jd1378** [comment]
thanks for reporting these
I have updated the regex to support these cases as well

will release in a few days

**Comment by duc2ht** [comment]
I just had another case where the content didn't use the word "code" or "otp", instead they used the word "mã"

_914 130 là mã Instagram của bạn và không được chia sẻ._

In this content, "mã" = "code", please add "mã" to sensitiveWords list
Thanks

**Comment by duc2ht** [comment]
After adding "mã" to sensitiveWords, I see a lot of false positives happening, Compared to the true positive rate, it's not worth adding it, please remove it, thank you

**Comment by jd1378** [comment]
Okay
