### ISSUE TITLE
App not working, although all permissions given

### ISSUE THREAD

**Issue by pikatchu2k3** [jd1378/otphelper#27]
After setting up the app and given all the permissions, I can't get the app to work. 
The built in test text message is not read by the app nor any other SMS. 

Unfortunately I can't create any debugs.

The problem might be the used device which is a Pixel with GrapheneOS with android 14.
The otphelper app has no restrictions or app hardening settings.

Latest app version 1.5.1

**Comment by jd1378** [comment]
Hi
The app actually does not read SMS, it reads notifications
so if you don't receive notifications for sms, it won't work

let me know if you have problem with reading notifications

my first suggestion is to revoke the "read notification" permission and grant it again

**Comment by Tal-Gordon** [comment]
Hi, I experience the bug as well. All permissions granted, notifications aren't being read. Running stock android 14 on Pixel 7, build number UP1A.231005.007.

Tried your suggestion, revoking "read notification" permission and regranting it again didn't work.

**Comment by jd1378** [comment]
I'll investigate this on android 14 emulator to see if it's a new problem with android 14 or something else

**Comment by jd1378** [comment]
thanks for reporting this
this was an issue with a small change in android 14
I have applied a fix, will release soon

-----------------

more info for those who are interested and for log:
the fix was quite simple
https://developer.android.com/about/versions/14/reference/compat-framework-changes
Under IMPLICIT_INTENTS_ONLY_MATCH_EXPORTED_COMPONENTS
> For apps targeting Android 14 (API level 34) and higher, components must be exported in order to invoke them through implicit intents

**Comment by jd1378** [comment]
released in [v1.6.0](https://github.com/jd1378/otphelper/releases/tag/v1.6.0)
