### ISSUE TITLE
Not OTP but recognized as OTP

### ISSUE THREAD

**Issue by duc2ht** [jd1378/otphelper#28]
Hello, when I play video https://youtu.be/68SZYtgFF94, app automatically recognizes the OTP code as "ss97" even though there is no OTP code, "ss97" can be recognized from the channel name of the video above : "bigboss97"
Sorry for my bad English, hope you can understand, thanks

**Comment by jd1378** [comment]
Hi
Some false positive is inevitable
 Simply add it to ignore list using the ignore button on notification

**Comment by duc2ht** [comment]
I know there will be mistakes, but if it can be fixed it would be good, this happens with videos whose names contain the word "code" and have number, even though that number is quite far from the word "code", I think  It's better to eliminate cases where the number and "code" are too far apart.

**Comment by jd1378** [comment]
Well idk
There are cases where code is immediately after the word, and there are cases where code is several words apart

How much is "too far apart"? It can be 3 words or 10 words

I'd like to ban word "Unicode" instead, i guess that would be a better option

**Comment by duc2ht** [comment]
yeah, but in the video above the otp code only has 2 characters which is 97, and it takes the word "ss" to make the length 4 characters. I think I should increase the length of the OTP to 3 or 4 or more

**Comment by jd1378** [comment]
what version are you on ?

**Comment by duc2ht** [comment]
> what version are you on ? in latest version it takes "ss97"
> 
> > I think I should increase the length of the OTP to 3 or 4 or more
> 
> it's already 4 characters at least in latest updates

Last version 1.6.0, 4 character, so it take "ss97". If it identifies only "97" from the time of recognition, it should be ignored and there will be no false positives

**Comment by jd1378** [comment]
well I did not understand what you mean exactly, but results of regex is not progressively matched, it's either "ss97" or nothing, which makes adding "unicode" to ignore list the only available option. I have applied the fix already, will release it in a week or so, as some other problem may show up meanwhile

**Comment by duc2ht** [comment]
Otp includes alphanumeric characters?  If so then I understand, thank you

**Comment by jd1378** [comment]
Yes, there are otp with alphanumeric characters

**Comment by adarsh1001** [comment]
Hey, got an SMS (advert) today in which "15" got recognised as an OTP. 

_Your FREE subscription is waiting. Claim your FREE access to 15  OTTs such as Sony LIV, Lionsgate Play, Fancode, Eros Now, hoichoi, ManoramaMAX, and many more on Airtel Xstream Play. Watch smashing hits like Agent,Pareshan ,Meet Cute on your mobile, tablet or TV._

**Comment by jd1378** [comment]
Well i don't agree
I think code should be matched as substring, since it can be used without any space sometimes in some scenarios, and some other languages may have it in their word as substring 
I think banning unusual words is a better approach for code keyword

**Comment by adarsh1001** [comment]
Hmm makes sense. Some languages don't use spaces and may write the word "code" in English. I've seen this in Japanese at least.
