### ISSUE TITLE
Recognition update

### ISSUE THREAD

**Issue by GEkuL** [jd1378/otphelper#29]
The app wasn't able to recognize code in the following message:
```
(s/n an p/n) 301674634: 5512 kods vada gasdis 5 wuTSi
```
Meaning:
```
(S/N or F/N) 301674634: 5512 code expires in 5 days
```
  
Could you please update the code recognition pattern?

**Comment by jd1378** [comment]
What is the language ?

**Comment by GEkuL** [comment]
@jd1378 
That's Latin transliteration from Georgian
You can play with it [here](https://www.lexilogos.com/keyboard/georgian_conversion.htm)

**Comment by jd1378** [comment]
does "kods" appear almost in every other message you receive in georgian as well ?

**Comment by GEkuL** [comment]
Forgot to say, I'm using 1.5.1 version from Fdroid. 

> does "kods" appear almost in every other message you receive in georgian as well ? 
Nope, it comes from time to time, depending on the institution. But unfortunately, this transliteration has some popularity here :(

> and does it appear alone as "kods" ?
I didn't see anything else yet, but I'll let you know if smth new appears

**Comment by jd1378** [comment]
it's okay, but you didn't answer the question

**Comment by jd1378** [comment]
oh I saw you did, but i was bugged into quote

**Comment by jd1378** [comment]
can you list 2 or 3 of the most common ones ? words that come with a code almost all the time ? I can add them to the word list

**Comment by GEkuL** [comment]
Yeah, 5512 h is the correct code

**Comment by jd1378** [comment]
released in [1.7.0](https://github.com/jd1378/otphelper/releases/tag/v1.7.0)

**Comment by GEkuL** [comment]
@jd1378 hi again, I got this message broken again.
I'm on 1.10.0 now, and the app recognizes:
301674634 as code, not the needed **5512**

Could you please fix that?

**Comment by jd1378** [comment]
please update to 1.12.0 
The test for `(s/n an p/n) 987789123: 123456 kods vada gasdis 5 wuTSi` is still passing, so I'm not sure whats the problem exactly
