### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by darkspacer** [jd1378/otphelper#32]
hey, I'd like to help you translate the application into Russian.
Here are the translated files:

[full_description.txt](https://github.com/jd1378/otphelper/files/13327496/full_description.txt)
[short_description.txt](https://github.com/jd1378/otphelper/files/13327497/short_description.txt)
[strings.json](https://github.com/jd1378/otphelper/files/13327498/strings.json)
[title.txt](https://github.com/jd1378/otphelper/files/13328870/title.txt)

**Comment by jd1378** [comment]
thanks for the translation, I will add it to the app

**Comment by jd1378** [comment]
@darkspacer I was checking the files, and it seems `title.txt` file content is incorrect

**Comment by darkspacer** [comment]
@jd1378 my bad
[title.txt](https://github.com/jd1378/otphelper/files/13328870/title.txt)

**Comment by jd1378** [comment]
title is more than 30 characters, if it's possible to reduce it to less or equal to 30, it would be nice
if not, It's still okay, I will remove the "- otp helper" part

**Comment by darkspacer** [comment]
@jd1378 yes, you can remove "OTP Helper" from the title

**Comment by jd1378** [comment]
released in [1.7.0](https://github.com/jd1378/otphelper/releases/tag/v1.7.0)
