### ISSUE TITLE
False positive detection when playing videos on twitter

### ISSUE THREAD

**Issue by Dev-iL** [jd1378/otphelper#38]
I was viewing a [video](https://twitter.com/yankicoen/status/1724613308651618572?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1724613308651618572%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=data%3Atext%2Fhtmlblockquoteclass%3Dtwitter-tweetahref%3Dhttps%3A%2F%2Ftwitter.com%2Fyankicoen%2Fstatus%2F1724613308651618572%2Fa%2Fblockquotescriptasyncsrc%3Dhttps%3A%2F%2Fplatform.twitter.com%2Fwidgets.jscharset%3Dutf-8%2Fscript) on X (twitter) through the Firefox app, and otphelper was triggered with the following payload:

```
2Fblockquotescriptasyncsrc
```

Note that it only happens when visiting the url that includes all the urlparams ("?ref_src" and everything that follows). When visiting the same tweet and playing the same video from a ["sanitized" url](https://twitter.com/yankicoen/status/1724613308651618572), this doesn't occurr.

Unless you developed a detection tool for malware/code injection, this seems like a false positive.

I'm on version 1.6.0

**Comment by jd1378** [comment]
Hi
Thanks for reporting this issue
I think the cause of this false positive is because of foreground notifications participating in code detection
The easiest general fix i can think of is to ignore all foreground notifications, which should drastically reduce such false positives

**Comment by jd1378** [comment]
released on [1.7.1](https://github.com/jd1378/otphelper/releases/tag/v1.7.1)

**Comment by Dev-iL** [comment]
Hello, not sure if related to the same issue or separate - I noticed that the app captures codes that arrive via IM, e.g. telegram. Is there a way to configure which apps I want to detect codes in (e.g. SMS only)?

**Comment by jd1378** [comment]
well you can use ignore button on the code detected notification to ignore detecting codes from notifications you do not want to receive

if the ignore is not working as expected, please let me know
