### ISSUE TITLE
Add apps to ignore list 

### ISSUE THREAD

**Issue by c4tb3rt** [jd1378/otphelper#40]
Whenever I get reminders for online meetings with a Teams or Zoomlink, the app deduces a part of the invite as an OTP. I would like to exclude my calendar app from Otp-scanning.

**Comment by jd1378** [comment]
Hmm, I see
I will change the behavior to ignore the app instead of using it's title to ignore, if it's not having a good tag, which should improve your experience of ignoring things

thanks for reporting this

**Comment by jd1378** [comment]
you have tried using the ignore button on the notification, right ?

**Comment by jd1378** [comment]
will be released in [v1.8.0](https://github.com/jd1378/otphelper/releases/tag/v1.8.0)
