### ISSUE TITLE
Can we add "PIN" as a matching word?

### ISSUE THREAD

**Issue by adarsh1001** [jd1378/otphelper#46]
I came across this yesterday, a popular on-demand service platform uses "PIN" instead of OTP or password in their SMS:

_<#> Welcome to Dunzo. Your PIN is 917778 1IofsghvRkq_

I'm not sure how many other services use "Pin" but it seems like a good-enough word to add to the matcher. What do you think?

**Comment by jd1378** [comment]
I feel like it might trigger false positives, so I'm not sure about adding it
I'd say let's see if more people report "PIN" keyword

**Comment by adarsh1001** [comment]
Hey @jd1378, how about "One Time Password"? I just came across this case for a popular cab company in India:

_Your One Time Password for user account with BluSmart is 222555. Valid for 10 Mins. For any assistance call <redacted>.
n4ZxQ3soH/R_

**Comment by jd1378** [comment]
Hi
I think this one is okay, I'll add when I have time

**Comment by jd1378** [comment]
closing since this was added at some point
