### ISSUE TITLE
Add detection log screen with ignore button

### ISSUE THREAD

**Issue by jd1378** [jd1378/otphelper#47]
> [Naomitr0n](https://github.com/Naomitr0n):

> What about adding toggleable otp logging that shows detected codes and what app sends them etc.? I remember a bug in an older version where every F-Droid update was detected, would be great to enable logging for a bit and add apps to ignore as needed from that -- plus keep track of what's actually being detected in case there's a use case that isn't being caught correctly or that isn't caught at all.

Made an issue from the comment from #33 to not forget about it

**Comment by doremonx** [comment]
I would like to drop a source code for you on my profile for selection of material UI that looks great over the theme for this , you should definitely visit & try these howers there, thank me at professor_x

**Comment by pataquets** [comment]
For usage scenarios where user has lots of notifications, this would enable a "learn mode"/"only whitelisted" usage, where you won't have to ignore _all but_ your SMS app, but just let it run for some time and later review the log to whitelist-only your desired apps.

**Comment by jd1378** [comment]
will be added on 1.16.0
you can try it now:
https://github.com/jd1378/otphelper/releases/tag/v1.16.0-rc
