### ISSUE TITLE
Doesn't detect OTP of Sacombank in Viet Nam

### ISSUE THREAD

**Issue by vufly** [jd1378/otphelper#48]
![Screenshot_20231212_235059.jpg](https://github.com/jd1378/otphelper/assets/20252099/7ae60e5b-6a5b-4ac1-8403-b779d15f8c5c)

So the message is
```
Quy khach se MAT TIEN va THONG TIN neu cung cap Ma xac thuc giao dich (OTP) cho bat ky ai. Ma OTP (het han sau 1 phut) cua Quy khach la 072-464
```

The OTP here was 072464. Could you add this pattern for detection?

**Comment by jd1378** [comment]
added to pattern and will be released with next version
