### ISSUE TITLE
OTP for e-carte blue not recognised 

### ISSUE THREAD

**Issue by testcocoon** [jd1378/otphelper#51]
The following OTP from SMS  are not recognised: 

Le code à saisir pour votre achat de 200,00 EUR est 29444635. Ne donnez ce code à personne. Si vous n'avez pas réalisé cet achat, appelez le 09.69.32.00.04.

29444635 is the OTP.

**Comment by jd1378** [comment]
sadly the first number appearing after "code" keyword is 200, which prevent the pattern from detecting the actual code

I can't change the pattern to fix this, as current requirement is that the first number after the sensitive keyword to be the code

**Comment by testcocoon** [comment]
You could extend the pattern to not consider the numbers followed by a currency symbol.
Something like this regularly expression:
code([a-z ]|([0-9.,]* *(EUR|USD))*[0-9]*

**Comment by jd1378** [comment]
part of the problem is that the app regex also takes a-zA-Z into account for codes, so it's not that simple

**Comment by testcocoon** [comment]
I will try to make a suggestion on regexp. 
I can then create a pull request. The only problem is that I cannot build your code. So I will validate the regex online and put it in the code directly. You will then need to review it.

**Comment by testcocoon** [comment]
I have added the following pattern:
`| ?[0-9,.]+ ?(EUR|[$€]|USD)`

It ignores its number followed by EUR, USB $ or €.
I have added it to the list of items to ignore. See the picture (part highlighted in yellow):
![Screenshot 2023-12-23 at 14-14-14 regex101 build test and debug regex (1)](https://github.com/jd1378/otphelper/assets/1838421/8bd22951-1822-49ed-8c3d-cb0a81de8773)

**Comment by jd1378** [comment]
sadly while it works in ecmascript version of the regex, it does not work in java
adding the change breaks all cases, and it doesn't even detect the code in the case it is trying to solve

**Comment by jd1378** [comment]
I'm still open to changing it if you did manage to find one that works and doesn't break other cases

**Comment by jd1378** [comment]
well I managed to change the pattern to detect this as well
