### ISSUE TITLE
Ignore not working for Outlook mails

### ISSUE THREAD

**Issue by sid-dev-97** [jd1378/otphelper#52]
App is copying codes in Outlook mails, ignore is not working as the tags are not unique and keep changing:
![tempFileForShare_20240102-120212](https://github.com/jd1378/otphelper/assets/129926798/5cb56c19-0414-47d9-b049-260be65b462b)

Also a suggestion --> Can you make a whitelist of apps, so that it copies codes from only these apps, instead of manually ignoring unwanted apps every time.

@jd1378

**Comment by jd1378** [comment]
Hmm
I'll try to separate the tag and app ignore buttons for next release
Introducing a whitelist requires permission to query all apps installed on the device, and a new screen for picking them, which is quite some work
It would be nice if someone made PR, i would review and merge if implementation is good

**Comment by jd1378** [comment]
separated buttons in in [v1.11.0](https://github.com/jd1378/otphelper/releases/tag/v1.11.0)
