### ISSUE TITLE
False positive related to dash-delimited strings

### ISSUE THREAD

**Issue by Dev-iL** [jd1378/otphelper#55]
Hello again,

Noticed the following issue both in v1.10 and v1.11: a string such as 

```
otp-helper--release-1.11.0--universal-14000-signed.apk
```

causes a "code" of `release1` to be detected.

**Comment by jd1378** [comment]
hi
this is ok
there's clearly "otp" in the message
in Chinese text there's usually no space, so this is a fine false positive

**Comment by Dev-iL** [comment]
Is there a test case that allows this behavior? If not, I suggest one is added with the reasoning you just provided mentioned in the docstring.

**Comment by jd1378** [comment]
example: https://github.com/jd1378/otphelper/blob/8c971ee9817fde3b8033594a05b3f6bee4e04757/app/src/test/java/io/github/jd1378/otphelper/CodeDetectionUnitTest.kt#L262

**Comment by Dev-iL** [comment]
Please let me clarify: the unittest I had in mind is one encodes the allowed false positive verbatim, i.e. given the string in top post it detects `release1` (w/o a dash before the number) as the code, and nothing else like 14000 etc.

Maybe also add a test that has a code like 1-2-3-4-5 captured as 12345 (somewhat similar to the space-delimited https://github.com/jd1378/otphelper/blob/8c971ee9817fde3b8033594a05b3f6bee4e04757/app/src/test/java/io/github/jd1378/otphelper/CodeDetectionUnitTest.kt#L376)

**Comment by jd1378** [comment]
well, whenever some code like that popped up let me know and I'll add a test and update the regex if needed
I don't want to eagerly update the regex when it's not needed
there was some case that had a dash between numbers though and it was handled:
https://github.com/jd1378/otphelper/blob/8c971ee9817fde3b8033594a05b3f6bee4e04757/app/src/test/java/io/github/jd1378/otphelper/CodeDetectionUnitTest.kt#L562
