### ISSUE TITLE
missing detection

### ISSUE THREAD

**Issue by kaduvert** [jd1378/otphelper#57]
While using the app today, i noticed that it didn't catch a code sent via SMS.

original (german):
```
Ihre smsTAN lautet 736194. Freundliche Grüße, [...]
```

translation:
```
Your smsTAN is 736194. Friendly regards, [...]
```

**Comment by jd1378** [comment]
that's because the "TAN" keyword is not separate from sms
to limit false positive TAN only works if it's a word on its own

**Comment by kaduvert** [comment]
i see...
how about making smsTAN a keyword?

**Comment by kaduvert** [comment]
#57
