### ISSUE TITLE
Not copy code

### ISSUE THREAD

**Issue by sinhy0** [jd1378/otphelper#59]
![IMG_20240112_235956_126.jpg](https://github.com/jd1378/otphelper/assets/149545509/ff355359-f87b-4bce-80d1-49a0ef83b9c8)

The App copy number from user name, NOT code

Thanks

**Comment by jd1378** [comment]
Hi
Can you copy the complete message here and change your username, so i can test on it ? 
Also please copy the mail subject

**Comment by sinhy0** [comment]
مرحبًا ‌ka_9090⁩،

يُرجى إدخال هذا الرمز في تطبيق سناب شات لتسجيل الدخول إلى حسابك:

888502

نرجو ألّا يطلع أحد على هذا الرمز، وأنْ تستخدمه داخل تطبيق سناب شات.

في حال لم تطلب هذا الرمز، فقد يكون هذا بسبب كتابة أحدهم لاسم المستخدم الخاص بك أو عنوان بريدك الإلكترونيّ عن طريق الخطأ. ننصحك بالتحقق من معلومات الاتصال خاصتك وتفعيل خاصية تسجيل الدخول بخطوتين مباشرةً في تطبيق سناب شات لزيادة درجة الأمن على حسابك.

ولن يتمكّن أحد من الدخول إلى حسابك على سناب شات باستثناء من يعرفون كلمة مرور حسابك أو من يستخدمون الرمز الذي يصل إلى هذا البريد الإلكتروني.

شكرًا لك،
فريق سناب شات
subject:

رمز التحقق من تسجيل الدخول إلى سناب شات: ⁦888502⁩

_______________________
the app copy ''9090'' from username, this app is "Samsung Email"
Thanks

**Comment by jd1378** [comment]
hmm, that's weird

I tried this in a test and it passed

are you on the latest version ?

**Comment by sinhy0** [comment]
> hmm, that's weird
> 
> I tried this in a test and it passed
> 
> are you on the latest version ?

I think YES, Thanks

**Comment by jd1378** [comment]
in which language your official telegram sent the code ? because I just tested it a few days ago and it certainly did copy just from the notification in english
