### ISSUE TITLE
Turkish Translation

### ISSUE THREAD

**Issue by SirCrownguard** [jd1378/otphelper#6]
Is there any file for translate?

For a reason I don't know, I cannot upload a TXT file. Here is a text file sharing service link: https://justpaste.it/azmjw

**Comment by jd1378** [comment]
Hi @SirCrownguard 
please translate these 3 files as well
https://github.com/jd1378/otphelper/blob/main/fastlane/metadata/android/en-US/full_description.txt
https://github.com/jd1378/otphelper/blob/main/fastlane/metadata/android/en-US/short_description.txt
https://github.com/jd1378/otphelper/blob/main/fastlane/metadata/android/en-US/title.txt

please note:
- max character limit for app title is 30 characters
- max character limit for short description it's 80 characters

these files are shown in google play store and f-droid

**Comment by jd1378** [comment]
@mention my username if you ever decided to also translate these files.
it's fine if you don't as well, the language is still shown inside the app
thanks for contributing :)

**Comment by SirCrownguard** [comment]
Sorry. I had a problem with my computer and couldn't help you for a long time. Now I'm here, I'll translate the remaining strings.

**Comment by SirCrownguard** [comment]
[full_description.txt](https://github.com/jd1378/otphelper/files/13053724/full_description.txt)
[short_description.txt](https://github.com/jd1378/otphelper/files/13053915/short_description.txt)
[title.txt](https://github.com/jd1378/otphelper/files/13053923/title.txt)

**Comment by jd1378** [comment]
can you shorten the short_description to be less than or equal to 80 characters ?  it's 83 characters right now

**Comment by jd1378** [comment]
also there seems to be a problem with title.txt, since it's same as short_description.txt

**Comment by SirCrownguard** [comment]
Sorry for that. Here's it all.
[short_description.txt](https://github.com/jd1378/otphelper/files/13056355/short_description.txt)
[title.txt](https://github.com/jd1378/otphelper/files/13056356/title.txt)

**Comment by jd1378** [comment]
hi
title is now exceeding 30 character (it's 33 chars) and its not same as "SMS Kodunu Kopyala" that you have provided in the first link in this issue
if the title cannot be shortened, we have to remove the "- OTP Yardımcısı" part and decide to use "SMS Kodunu Kopyala"  or "SMS Kodu Kopyala"

**Comment by SirCrownguard** [comment]
You can use "SMS Kodu Kopyala".
