### ISSUE TITLE
Translate Arabic is done!

### ISSUE THREAD

**Issue by Bunny-77X** [jd1378/otphelper#60]
**Hi dev**

I have translated the app into Arabic ( العربية ) 

[Copy SMS Code (Arabic translation).zip](https://github.com/jd1378/otphelper/files/13933593/Copy.SMS.Code.Arabic.translation.zip)

**Thank you for this great app ♡**

**Comment by jd1378** [comment]
Hi
thanks for translating the app
can you also translate the app name to Arabic ? since it's a generic keyword targeted app name, it should translatable

thank you for contributing
