### ISSUE TITLE
没有自动复制验证码

### ISSUE THREAD

**Issue by 3001-dot** [jd1378/otphelper#67]
你好！
这条消息没有被自动复制验证码，请问可以添加上吗？
>【米哈游】验证码：206623（10分钟内有效）。您正在关闭新设备验证功能，请勿将验证码告诉他人哦。

**Comment by jd1378** [comment]
Hi
this message is already supported by the app (I have added a test just in case to make sure)
the app works by reading the notifications, so either you didn't receive a notifications, OR, the app had a problem reading the notification
