### ISSUE TITLE
Cannot copy the code individually.

### ISSUE THREAD

**Issue by puppet680** [jd1378/otphelper#68]
The sensitive word "123456code" cannot be recognized.
The sensitive word "123456 code" can be recognized if a space is added here.

**Comment by jd1378** [comment]
Hi
please always provide the original message for testing

**Comment by puppet680** [comment]
text :【哔哩哔哩】492291短信登录验证码，5分钟内有效，请勿泄露。

**Comment by jd1378** [comment]
thank you
fixed it in [v1.13.4](https://github.com/jd1378/otphelper/releases/tag/v1.13.4)
