### ISSUE TITLE
Hungarian translation

### ISSUE THREAD

**Issue by kekmacska** [jd1378/otphelper#73]
Hello jd1378!

I have made a hungarian translation for the Copy SMS Code app. The descriptions and title are done, too. I send them as a mediafire link. The xml and the 3 txt files are packed in [this](https://www.mediafire.com/file/3r0l0ejc0rr3ixr/copy_sms_code_1-3-4_hu_translation.zip/file) zip file, since Github doesn't let me upload them directly. (Upload location is US, since i use a vpn.) If you accept my translation, please implement it to your app. I'm kindly waiting for your response. Thank you

PS.: Proof that i'm not sending a zip bomb:
https://www.virustotal.com/gui/file-analysis/NzkxOWFjZmQyY2FlMmZhZTg4ZmIyMzM4MmU5ZTUwMzk6MTcxMjgzODEwNw==

**Comment by jd1378** [comment]
Hi
Thank you for putting time
And thanks for knowing that this seems suspicious 😅
Please put your text on pastebin or hastebin, where the text does not need to be downloaded and put the links here
That way I won't need to download a file

**Comment by jd1378** [comment]
I'm sorry but as I'm not seeing activity on this, im closing it

feel free to add your translation through weblate
