### ISSUE TITLE
Option to ignore entire app instead of just notification type

### ISSUE THREAD

**Issue by Naomitr0n** [jd1378/otphelper#75]
Feature request: change the "Ignore app" button on the notification to give you the option to ignore only the app's notification type, or just the app as a whole. That way someone can pick between the "only this type of notification" option `app:com.google.android.keep:nid:4` or the more broad "entire app" version `app:com.google.android.keep` depending on their needs

[ Migrated from #74 ]

**Comment by jd1378** [comment]
hmm, I had added two buttons, one was for app, one for notification tag
maybe I can make it fallback to notification Id if there's no tag, so we can keep it 2 buttons but still get the functionality

**Comment by jd1378** [comment]
sadly the notification actions are limited in what can be done
but I fixed the behavior for "ignore app" button to actually ignore the entire app in v1.15.0
