### ISSUE TITLE
Vietnamese translate!

### ISSUE THREAD

**Issue by Sharethebest** [jd1378/otphelper#8]
[This is](https://github.com/Sharethebest/translate) the Vietnamese translation file that I created because it is not included in your application, hope you will accept it.

**Comment by jd1378** [comment]
hi @Sharethebest 

thanks for the contribution

sadly the short description you provided is exceeding 80 characters limit, please shorten it
also the main translation for the app ui is this file:
https://github.com/jd1378/otphelper/blob/main/app/src/main/res/values/strings.xml

please translate the file above so we can add the translations to the app

**Comment by Sharethebest** [comment]
> hi @Sharethebest
> 
> thanks for the contribution
> 
> sadly the short description you provided is exceeding 80 characters limit, please shorten it also the main translation for the app ui is this file: https://github.com/jd1378/otphelper/blob/main/app/src/main/res/values/strings.xml
> 
> please translate the file above so we can add the translations to the app
Hi, I have edited the short desc and translated strings.xml

[Here is the link](https://github.com/Sharethebest/translate)

**Comment by jd1378** [comment]
thank you :) 
it has been [added to the app](https://github.com/jd1378/otphelper/commit/db5e2a7b96e75c3517d555dc58628e9b58459d9f), will be available in next release

**Comment by Sharethebest** [comment]
@jd1378 Bro, new version already have auto translate or nothing new added? I dont know how to see which not translated yet :>

**Comment by jd1378** [comment]
Hey
I think I added 2-3 new strings, but I translated them manually using Google translate
If everything looks fine then I guess it was fine 😁
Usually new strings are added at the end of each strings.xml of each locale
For Vi its this file:
https://github.com/jd1378/otphelper/blob/main/app/src/main/res/values-vi/strings.xml
