### ISSUE TITLE
problem with code from sms

### ISSUE THREAD

**Issue by boy2friend** [jd1378/otphelper#81]
Completely ignores the code from SMS of this format:
10.04.2024 10:18 Parol dlya podtverzhdeniya: 09890. Perevod 800.00 RUB.

**Comment by jd1378** [comment]
what is the sensitive keyword in this sms ?

**Comment by boy2friend** [comment]
Сode from this sms: 09890
All sms messages from this sender look the same. Only these digits "09890" are changed.

**Comment by jd1378** [comment]
Hi
You did not answer my questions
I need to know which word means "code" in that language

**Comment by boy2friend** [comment]
"Parol dlya podtverzhdeniya" is a common phrase written in transliteration of the russian language. It is translated as "Password for confirmation" and does not change in each SMS.

**Comment by jd1378** [comment]
thank you, I'll add it in the next version

**Comment by jd1378** [comment]
added in [1.15.3](https://github.com/jd1378/otphelper/releases/tag/v1.15.3)
