### ISSUE TITLE
希望添加自动输入功能

### ISSUE THREAD

**Issue by wa0002** [jd1378/otphelper#89]
希望添加验证码自动输入功能

**Comment by jd1378** [comment]
this is not possible in android
at best this app can only suggest, which is pointless as clipboard content is usually suggested by your keyboard anyway

**Comment by wa0002** [comment]
![Screenshot_2024-05-23-09-36-20-37_b226428adf9b3459d7445ba6ec12f9f5](https://github.com/jd1378/otphelper/assets/77516343/fc1319db-115e-4ec6-bf00-9d855b82866e)
这个模块就可以实现，但是无法获取其他app验证码

**Comment by jd1378** [comment]
If you mean as autofill service, yes it is pointless

**Comment by jd1378** [comment]
If the app requires accessibility permissions, then google play store will probably reject it

**Comment by jd1378** [comment]
I will check the app you mentioned when I have time to make sure

**Comment by jd1378** [comment]
I have checked the app you mentioned and it looks like to be possible without any special permission
I will try it when I have time
thanks for letting me know

**Comment by jd1378** [comment]
it seems I was wrong and it requires the device to be rooted and Xposed Framework installed, which I don't think I'm gonna add support for any time soon.
