### ISSUE TITLE
[Feature Request] Please, add Amoled Black theme option for in-app Dark mode

### ISSUE THREAD

**Issue by Username1-a** [jd1378/otphelper#95]
Hello, please, if it's not too burdensome, add an option for Black in-app theme in Dark mode for Copy SMS Code (Just for aesthetics and consistency, basically), like how some 3rd party Material You supported apps are doing (LSposed, Swift Backup, Material Files, aShell You, etc)

In version 1.13.1 the app background brightness followed Monet theme that you can change in app like Repainter or in custom ROM settings, but in version 1.13.3 and onward (probably because of updated material components – a very unfortunate change by google) app's background in Dark mode always stays grey

Comparison:

![Screenshot_20240408-184114_Copy SMS Code~3](https://github.com/jd1378/otphelper/assets/47947180/7eec732d-b9e5-457a-9be8-a1bf6977b418)

![Screenshot_20240408-184024_Copy SMS Code~3](https://github.com/jd1378/otphelper/assets/47947180/db63b0fb-f6f6-4d8d-8bdc-54010dd2af13)

Good luck

**Comment by jd1378** [comment]
Hi
this is indeed sad, I just update my dependencies regularly
adding themes for such a basic app, which most of it's usage time is when it's not seen at all, is kind of overkill

I'm open to contributions in case someone likes to implement it, but I can't put time on it when other essential features (like detection history) are still not implemented yet
