### ISSUE TITLE
Can the SMS verification code be automatically copied even when the screen is locked?

### ISSUE THREAD

**Issue by deng-dengdengdeng-deng** [jd1378/otphelper#99]
A scenario: Using a Mac and an Android phone, when the Android phone is not nearby, the Mac sends a verification code. Currently, the phone will not be copied when the screen is locked, and the verification code must be manually picked up to unlock the screen.Because I am using an input method that allows multiple devices to synchronize the clipboard, I can directly paste verification codes on the Mac without opening my phone.

**Comment by jd1378** [comment]
Hi
if the application is able to read notifications when the phone is locked, it will work, which I am not aware if android allows such behavior or not

are you sure your clipboard sync works when the phone is locked? many apps do not work because android phones usually put them to sleep very fast unless they are excluded from battery optimizations

after checking that, if it's not working, then probably android is not working the way we expect it

you can check if it's working by locking your phone, sending your sms, and then unlocking the phone after 10 seconds and try to paste it somewhere to see if it has worked or not

if the code is copied, then most likely your sync is at fault

**Comment by deng-dengdengdeng-deng** [comment]
> Hi if the application is able to read notifications when the phone is locked, it will work, which I am not aware if android allows such behavior or not
> 
> are you sure your clipboard sync works when the phone is locked? many apps do not work because android phones usually put them to sleep very fast unless they are excluded from battery optimizations
> 
> after checking that, if it's not working, then probably android is not working the way we expect it
> 
> you can check if it's working by locking your phone, sending your sms, and then unlocking the phone after 10 seconds and try to paste it somewhere to see if it has worked or not
> 
> if the code is copied, then most likely your sync is at fault



> Hi if the application is able to read notifications when the phone is locked, it will work, which I am not aware if android allows such behavior or not
> 
> are you sure your clipboard sync works when the phone is locked? many apps do not work because android phones usually put them to sleep very fast unless they are excluded from battery optimizations
> 
> after checking that, if it's not working, then probably android is not working the way we expect it
> 
> you can check if it's working by locking your phone, sending your sms, and then unlocking the phone after 10 seconds and try to paste it somewhere to see if it has worked or not
> 
> if the code is copied, then most likely your sync is at fault

Im using weixin type https://z.weixin.qq.com/, I have tried lock phone and send sms on my mac, code cant be copied, after unlocking my phone ,code immediately copied and then i can copy on my mac. how can i test when my phone locking ,if the sync work, i will try it.

**Comment by jd1378** [comment]
you mean you see the toast/notification about code being copied by the app immediately as you open the phone ?

**Comment by deng-dengdengdeng-deng** [comment]
> you mean you see the toast/notification about code being copied by the app immediately as you open the phone ?

Yes, i try to send sms on my mac, dont unlock my phone and the code cant copy on mac. When i unlock my phone , code copied immediately and i can immediately copy the code on my mac.

**Comment by jd1378** [comment]
can you try [v1.16.0-rc](https://github.com/jd1378/otphelper/releases/tag/v1.16.0-rc) to see if it helps with anything?

**Comment by deng-dengdengdeng-deng** [comment]
> can you try [v1.16.0-rc](https://github.com/jd1378/otphelper/releases/tag/v1.16.0-rc) to see if it helps with anything?

also need unlock my phone to copy code.

**Comment by deng-dengdengdeng-deng** [comment]
> sad to hear I don't think there's much I can do sounds like an issue with your syncing app maybe ask on their side about it?

thanks for your trying.
When phone was locked, only sms notifications on my screen,when i unlock ,this app shows "code copy", i dont know whether this app works before the "code copy" shows.
maybe the reason is syncing app doesnt work when phone locked.

**Comment by BackMountainDevil** [comment]
weixin input method is not recommend to use because of [data leak](https://www.bilibili.com/video/BV17U4y1z71K/)

**Comment by BackMountainDevil** [comment]
"multiple devices to synchronize the clipboard" try KDE Connect or buy one iphone...

**Comment by jd1378** [comment]
closed as I cannot solve this
